### ISSUE TITLE
Type conversion error at archive_read_data_block

### ISSUE THREAD

**Issue by srib** [google/bazel#109]
I tried to compile bazel on Ubuntu Trusty 14.04, i686.

I get this compilation error:

```
Compiling client .cc files...
src/main/cpp/blaze.cc: In function ‘void blaze::ActuallyExtractData(const string&, const string&)’:
src/main/cpp/blaze.cc:806:71: error: cannot convert ‘off_t* {aka long int*}’ to ‘int64_t* {aka long long int*}’ for argument ‘4’ to ‘int archive_read_data_block(archive*, const void**, size_t*, int64_t*)’
       retval = archive_read_data_block(blaze_zip, &buf, &size, &offset);
```
I fixed it using static casting int64_t to long long int.

```
long long int offset1 = static_cast<int64_t> (offset);
retval = archive_read_data_block(blaze_zip, &buf, &size, &offset1);
```
Is there a better fix for this?

**Comment by damienmg** [comment]
hanwen did a change to that I think we have to roll it back. We don't have 32 bit machine so it is a bit tricky to debug.

**Comment by ulfjack** [comment]
Hanwen's change isn't live yet (sorry!).

**Comment by damienmg** [comment]
Indeed my bad. So hopefully it should be solved when the change come live.

**Comment by ulfjack** [comment]
Should be live now.

**Comment by srib** [comment]
The problem hasn't been fixed. I still get the same error message.

**Comment by damienmg** [comment]
The change isn't live yet.

**Comment by ulfjack** [comment]
Sorry about that.

**Comment by hanwen** [comment]
fixed by https://github.com/google/bazel/commit/8d676c54644b7213a926faa00fc793e0e23fad0b

(I thought github would autoclose the issues?)

**Comment by damienmg** [comment]
8d676c5 refer to bug #18 not this one.
