### ISSUE TITLE
py_binary always use python as the interpreter when PY3 is specified

### ISSUE THREAD

**Issue by mzhaom** [google/bazel#200]
My build rule:
```
py_binary(
  name = 'compile_asn',
  srcs = [
    'compile_asn.py'
  ],
  default_python_version = 'PY3',
  srcs_version = 'PY3',
)
```

I expect the generated wrapper script would use python3 as the interpreter but actual it still uses python:
```
#!/bin/bash -eu

STUBPATH=$(python -c "import os.path; print os.path.realpath('$0');")
export PYTHONPATH=$STUBPATH.runfiles
python ${PYTHONPATH}/lte/asn/compile_asn.py $@
```

Is there any way to have some knob to control which python interpreter to use?

**Comment by hanwen** [comment]
should be fixed by

**Comment by hanwen** [comment]
https://github.com/mzhaom/bazel/commit/f08d7fc81a3ff1f0010863126aaaaaacd7f59e66

**Comment by JoeHazzers** [comment]
It doesn't look like that commit ever made it into upstream (i.e. here), no?

I'm still experiencing the same issues against HEAD

**Comment by lberki** [comment]
I just tried with a small rule:

```
py_binary(
    name = "a",
    srcs = ["a.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
)
```

And it properly exec()s python3. The shebang line is `#!/usr/bin/python`, though, but that should not influence which Python interpreter the actual binary is executed with. Am I holding it wrong?

**Comment by raliste** [comment]
Was the fix merged into bazel? My only workaround is setting the python_path flag to /usr/local/bin/python3

**Comment by brandjon** [comment]
FYI I believe this was fixed and regressed, and is now a dup of #4815.
