### ISSUE TITLE
Can't fetch Maven dependencies after recent change

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#224]
I just updated my Bazel installation, and builds that were working before are now failing with this error:

```
error loading package 'external': Failed to fetch Maven dependency: Could not transfer artifact com.google.guava:guava:jar:18.0 from/to user-defined repository (): Cannot access  with type default using the available connector factories: BasicRepositoryConnectorFactory and referenced by '//src/main/java/annotationprocessors:annotationprocessors'.
```

The culprit seems to be 512e91f288ca15197474adcc3dfe1a7a2a28203c, which added SHA checksums. Building at that commit fails even if I cherrypick 1170dc6055ed0d669275efb1ab1906d2715ad1c3 to make the checksums optional. Building at the previous commit (6d98f6c633ec4a12737544a149bc18c41a3c442a) succeeds

@kchodorow

**Comment by kchodorow** [comment]
My bad, @michajlo has a fix for this.

**Comment by kchodorow** [comment]
Fixed by 2cd174b87a8eb5318b9768eb84fde5c6eec731a8.

**Comment by ekuefler** [comment]
I'm still having a problem that I think is closely related:

```
no such package 'external': Downloaded file at /private/var/tmp/_bazel_erik/61b955331c7adf0d4763dcd1923ddf38/external/javax-inject_maven/javax/inject/javax.inject/1/javax.inject-1.jar has SHA-1 of 6975da39a7040257bd51d21a231b76c915872d38, does not match expected SHA-1 () and referenced by '//src/main/java/com/api/device/actions:actions'.
```

Looks like if SHA1 isn't specified it's comparing it to an empty string instead of ignoring it.
