### ISSUE TITLE
Internal compiler errors when enabling several error-prone flags

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#266]
When enabling several error-prone checks, I get internal compiler errors (including links to a google-internal URL) from Bazel when I try to build anything:

With `--javacopt="-Xep:OverridesGuiceInjectableMethod:ERROR"`
```
An exception has occurred in the compiler (1.9.0-internal_bootstrap). Please file a bug with the Java Platform Team (http://b.corp.google.com/createIssue?component=38990)  Include the following stack trace in your report.  Thank you.
java.lang.NullPointerException
	at com.google.errorprone.bugpatterns.GuiceOverridesGuiceInjectableMethod.isAnnotatedWith(GuiceOverridesGuiceInjectableMethod.java:93)
	at com.google.errorprone.bugpatterns.GuiceOverridesGuiceInjectableMethod.matchMethod(GuiceOverridesGuiceInjectableMethod.java:80)
	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:823)
	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:143)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:869)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:120)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:587)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:143)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:779)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:81)
	at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:137)
	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:111)
	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:167)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:93)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1272)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:866)
	at com.sun.tools.javac.main.Main.compile(Main.java:249)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:125)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:118)
	at com.google.devtools.build.buildjar.javac.JavacRunnerImpl.invokeJavac(JavacRunnerImpl.java:44)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:58)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.internalCompileJavaLibrary(AbstractJavaBuilder.java:117)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.access$000(AbstractJavaBuilder.java:40)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder$1.run(AbstractJavaBuilder.java:86)
	at java.lang.Thread.run(Thread.java:745)
java.io.IOException: Error compiling java source: java compilation returned status ABNORMAL
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.compileJavaLibrary(AbstractJavaBuilder.java:96)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.run(AbstractJavaBuilder.java:165)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:104)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:47)
```

With `build --javacopt="-Xep:OverridesJavaxInjectableMethod:ERROR"`:
```
An exception has occurred in the compiler (1.9.0-internal_bootstrap). Please file a bug with the Java Platform Team (http://b.corp.google.com/createIssue?component=38990)  Include the following stack trace in your report.  Thank you.
java.lang.NullPointerException
	at com.google.errorprone.bugpatterns.GuiceOverridesGuiceInjectableMethod.isAnnotatedWith(GuiceOverridesGuiceInjectableMethod.java:93)
	at com.google.errorprone.bugpatterns.GuiceOverridesGuiceInjectableMethod.matchMethod(GuiceOverridesGuiceInjectableMethod.java:80)
	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:823)
	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:143)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:869)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:120)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:587)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:143)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:779)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:81)
	at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:137)
	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:111)
	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:167)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:93)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1272)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:866)
	at com.sun.tools.javac.main.Main.compile(Main.java:249)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:125)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:118)
	at com.google.devtools.build.buildjar.javac.JavacRunnerImpl.invokeJavac(JavacRunnerImpl.java:44)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:58)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.internalCompileJavaLibrary(AbstractJavaBuilder.java:117)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.access$000(AbstractJavaBuilder.java:40)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder$1.run(AbstractJavaBuilder.java:86)
	at java.lang.Thread.run(Thread.java:745)
java.io.IOException: Error compiling java source: java compilation returned status ABNORMAL
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.compileJavaLibrary(AbstractJavaBuilder.java:96)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.run(AbstractJavaBuilder.java:165)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:104)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:47)
```

With `--javacopt="-Xep:ParameterPackage:ERROR"`:
```
An exception has occurred in the compiler (1.9.0-internal_bootstrap). Please file a bug with the Java Platform Team (http://b.corp.google.com/createIssue?component=38990)  Include the following stack trace in your report.  Thank you.
java.lang.NullPointerException
	at com.google.errorprone.bugpatterns.WrongParameterPackage.matchMethod(WrongParameterPackage.java:81)
	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:823)
	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:143)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:869)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:120)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:587)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:143)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:779)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:81)
	at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:137)
	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:111)
	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:167)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:93)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1272)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:866)
	at com.sun.tools.javac.main.Main.compile(Main.java:249)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:125)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:118)
	at com.google.devtools.build.buildjar.javac.JavacRunnerImpl.invokeJavac(JavacRunnerImpl.java:44)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:58)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.internalCompileJavaLibrary(AbstractJavaBuilder.java:117)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.access$000(AbstractJavaBuilder.java:40)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder$1.run(AbstractJavaBuilder.java:86)
	at java.lang.Thread.run(Thread.java:745)
java.io.IOException: Error compiling java source: java compilation returned status ABNORMAL
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.compileJavaLibrary(AbstractJavaBuilder.java:96)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.run(AbstractJavaBuilder.java:165)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:104)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:47)
```

**Comment by damienmg** [comment]
That's coming from the error-prone javac.

**Comment by cushon** [comment]
@ekuefler, is your bazel synced past 7ae29d2617e1039380df2b8fb3ee45286ba64dab?

The crashy checks are all experimental. Just to confirm - you're only seeing this after explicitly opting in to those checks, right?

**Comment by ekuefler** [comment]
Yes and yes. I'm synced at 1a8576a5dc8e0a1b04bcb230cc4f6c0f962fb8e4, which is later than that commit. I only see the exceptions if I explicitly opt in via the flags above.

**Comment by damienmg** [comment]
Should have been resolved by cd3df4cc9161fe8cc94293b8b856e0927a6b70ab

**Comment by cushon** [comment]
Note that cd3df4c improves the error message, but does not fix the crashes. I filed bugs against Error Prone for those.

Note that using experimental checks isn't really recommended -- they're categorized that way because they're buggy (as you discovered), or because they haven't been shown to be useful.

Thanks for taking the time to try them out and file bugs, though.

**Comment by damienmg** [comment]
It's no longer a Bazel issue anymore so we are good. Do you have the link to the issue from Error Prone?

**Comment by cushon** [comment]
Github shows links a couple of comments up: "This was referenced ..."

The issues are:

* google/error-prone/issues/354
* google/error-prone/issues/355
* google/error-prone/issues/356

**Comment by damienmg** [comment]
Thank you Liam. Erik: if you want to have follow-up, just subscribe to the
related issue on error-prone.

**Comment by ekuefler** [comment]
Thanks, sounds good. I don't have any pressing need for these checks, just kicking the tires.
